name: Publish to the GitHub Container registry

on:
  workflow_dispatch:
    inputs:
      version:
        description: Elasticsearch version

        required: true

        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v4
      # https://github.com/marketplace/actions/docker-setup-qemu
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # https://github.com/marketplace/actions/build-and-push-docker-images
      - uses: docker/build-push-action@v5
        with:
          context: .

          build-args: ELASTIC_VERSION=${{ inputs.version }}

          push: true

          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}:latest
            ${{ env.REGISTRY }}/${{ github.repository }}:${{ inputs.version }}

      - name: Inspect image
        run: docker inspect ${{ env.REGISTRY }}/${{ github.repository }}:${{ inputs.version }}

    env:
      REGISTRY: ghcr.io
